image: python:3.8

stages:
  - build
  - test
  - deploy

variables:
  VIRTUAL_ENV: "venv"

before_script:
  # Set up the virtual environment
  - python -m venv $VIRTUAL_ENV
  - source $VIRTUAL_ENV/bin/activate
  - pip install --upgrade pip

build:
  stage: build
  script:
    - echo "Building the project..."
    - python main.py
test:
  stage: test
  script:
    - echo "Running tests..."
    - python main.py
  dependencies:
    - build
deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
  only:
    - master
